# Autogenerated by build system
.global paijsdoiajsoidasrint; .type paijsdoiajsoidasrint, %function; paijsdoiajsoidasrint = 1;
.int 1
.string "paijsdoiajsoidasrint"

.global fat; .type fat, %function; fat = 2;
.int 2
.string "fat"

